/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Proyecto;

import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Pablo
 */
public class Bioapp extends javax.swing.JFrame {

    /**
     * Creates new form Bioapp
     */
    public Bioapp() {
        initComponents();
         dos.setVisible(true);
        tres.setVisible(false);
        cuatro.setVisible(false);
        this.setLocationRelativeTo(null);
        ImageIcon imagen17=new ImageIcon(getClass().getResource("/imagen/fondo.jpg"));
        Icon fondo17= new ImageIcon(imagen17.getImage().getScaledInstance(fondo.getWidth(),fondo.getHeight(),Image.SCALE_DEFAULT));
        fondo.setIcon(fondo17);
        this.repaint();
        
    }
    public Image getIconImage(){
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagen/cromosomas (Copiar).png"));
        return retValue;
    }

    public void e(){
    String e,i,E,I;
        E=A.getText();
        I=B.getText();
        e=a.getText();
        i=b.getText();

        Aa.setText(E+""+e);
        Bb.setText(e+""+I);
        Cc.setText(E+""+i);
        Dd.setText(I+""+i);
}
    public void x(){
    String a,aa,aaa,b,bb,bbb;
        a=A1.getText();
        aa=B1.getText();
        aaa=C1.getText();
        b=b1.getText();
        bb=a1.getText();
        bbb=c1.getText();

        Cc2.setText(a+""+b);
        Aa63.setText(a+""+bb);
        Aa53.setText(a+""+bbb);
        Dd3.setText(aa+""+b);
        Bb2.setText(aa+""+bb);
        Aa55.setText(aa+""+bbb);
        Aa59.setText(aaa+""+b);
        Aa48.setText(aaa+""+bb);
        Aa67.setText(aaa+""+bbb);
}
    public void i(){
    String a,aa,aaa,aaaa,b,bb,bbb,bbbb;
        a=A2.getText();
        aa=B2.getText();
        aaa=C2.getText();
        aaaa=D2.getText();
        b=a2.getText();
        bb=b2.getText();
        bbb=c2.getText();
        bbbb=d2.getText();

        l1.setText(a+""+b);
        l2.setText(a+""+bb);
        l3.setText(a+""+bbb);
        l4.setText(a+""+bbbb);    
        l5.setText(aa+""+b);
        l6.setText(aa+""+bb);
        l7.setText(aa+""+bbb);
        l8.setText(aa+""+bbbb);
        l9.setText(aaa+""+b);
        l10.setText(aaa+""+bb);
        l11.setText(aaa+""+bbb);
       l12.setText(aaa+""+bbbb);
        l13.setText(aaaa+""+b);
        l14.setText(aaaa+""+bb);
        l15.setText(aaaa+""+bbb);

        l16.setText(aaaa+""+bbbb);
       
}
    void mensaje(){
         String a,b,c,d,los;
        a=l1.getText();
        b=l6.getText();
        c=l11.getText();
        d=l16.getText();
         JOptionPane.showMessageDialog(null,  "La obtencion de la primare generacion es \n"+a+","+b+","+c+","+d);
    }
    void mensaje2(){
        String a,b,c;
        a=Aa63.getText();
        b=Dd3.getText();
        c=Aa67.getText();
        
         JOptionPane.showMessageDialog(null,  "La obtencion de la primare generacion es \n"+a+","+b+","+c);
    }
    void mensaje3(){
        String a,b;
        a=Aa.getText();
        b=Dd.getText();
        
        
         JOptionPane.showMessageDialog(null,  "La obtencion de la primare generacion es \n"+a+","+b); 
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        btnCerrar = new javax.swing.JButton();
        btnMinimizar = new javax.swing.JButton();
        inicio = new javax.swing.JPanel();
        dos = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        Bb = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        Cc = new javax.swing.JLabel();
        B = new javax.swing.JTextField();
        A = new javax.swing.JTextField();
        a = new javax.swing.JTextField();
        b = new javax.swing.JTextField();
        Aa = new javax.swing.JTextField();
        Dd = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        tres = new javax.swing.JPanel();
        jPanel59 = new javax.swing.JPanel();
        jPanel60 = new javax.swing.JPanel();
        Aa48 = new javax.swing.JLabel();
        jPanel61 = new javax.swing.JPanel();
        Aa49 = new javax.swing.JLabel();
        jPanel62 = new javax.swing.JPanel();
        Aa50 = new javax.swing.JLabel();
        jPanel63 = new javax.swing.JPanel();
        Aa51 = new javax.swing.JLabel();
        jPanel64 = new javax.swing.JPanel();
        Bb2 = new javax.swing.JLabel();
        jPanel66 = new javax.swing.JPanel();
        Cc2 = new javax.swing.JLabel();
        A1 = new javax.swing.JTextField();
        a1 = new javax.swing.JTextField();
        jPanel68 = new javax.swing.JPanel();
        Aa53 = new javax.swing.JLabel();
        jPanel69 = new javax.swing.JPanel();
        Aa54 = new javax.swing.JLabel();
        jPanel70 = new javax.swing.JPanel();
        Aa55 = new javax.swing.JLabel();
        jPanel71 = new javax.swing.JPanel();
        Aa56 = new javax.swing.JLabel();
        jPanel72 = new javax.swing.JPanel();
        Aa57 = new javax.swing.JLabel();
        jPanel73 = new javax.swing.JPanel();
        Aa58 = new javax.swing.JLabel();
        jPanel74 = new javax.swing.JPanel();
        Aa59 = new javax.swing.JLabel();
        jPanel75 = new javax.swing.JPanel();
        Aa60 = new javax.swing.JLabel();
        jPanel76 = new javax.swing.JPanel();
        Aa61 = new javax.swing.JLabel();
        jPanel77 = new javax.swing.JPanel();
        Aa62 = new javax.swing.JLabel();
        b1 = new javax.swing.JTextField();
        c1 = new javax.swing.JTextField();
        B1 = new javax.swing.JTextField();
        C1 = new javax.swing.JTextField();
        Aa67 = new javax.swing.JTextField();
        Aa63 = new javax.swing.JTextField();
        Dd3 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        cuatro = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        l10 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        Aa2 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        Aa5 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        Aa6 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        l5 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        l2 = new javax.swing.JLabel();
        D2 = new javax.swing.JTextField();
        A2 = new javax.swing.JTextField();
        a2 = new javax.swing.JTextField();
        d2 = new javax.swing.JTextField();
        jPanel17 = new javax.swing.JPanel();
        l3 = new javax.swing.JLabel();
        jPanel18 = new javax.swing.JPanel();
        Aa7 = new javax.swing.JLabel();
        jPanel19 = new javax.swing.JPanel();
        l7 = new javax.swing.JLabel();
        jPanel20 = new javax.swing.JPanel();
        Aa9 = new javax.swing.JLabel();
        jPanel21 = new javax.swing.JPanel();
        Aa10 = new javax.swing.JLabel();
        jPanel22 = new javax.swing.JPanel();
        Aa11 = new javax.swing.JLabel();
        jPanel23 = new javax.swing.JPanel();
        l9 = new javax.swing.JLabel();
        jPanel24 = new javax.swing.JPanel();
        Aa13 = new javax.swing.JLabel();
        jPanel25 = new javax.swing.JPanel();
        Aa14 = new javax.swing.JLabel();
        jPanel26 = new javax.swing.JPanel();
        Aa15 = new javax.swing.JLabel();
        jPanel35 = new javax.swing.JPanel();
        l13 = new javax.swing.JLabel();
        jPanel36 = new javax.swing.JPanel();
        Aa25 = new javax.swing.JLabel();
        jPanel37 = new javax.swing.JPanel();
        Aa26 = new javax.swing.JLabel();
        jPanel38 = new javax.swing.JPanel();
        Aa27 = new javax.swing.JLabel();
        jPanel39 = new javax.swing.JPanel();
        l14 = new javax.swing.JLabel();
        jPanel40 = new javax.swing.JPanel();
        Aa29 = new javax.swing.JLabel();
        jPanel41 = new javax.swing.JPanel();
        Aa30 = new javax.swing.JLabel();
        jPanel42 = new javax.swing.JPanel();
        Aa31 = new javax.swing.JLabel();
        jPanel43 = new javax.swing.JPanel();
        l15 = new javax.swing.JLabel();
        jPanel44 = new javax.swing.JPanel();
        Aa33 = new javax.swing.JLabel();
        jPanel45 = new javax.swing.JPanel();
        Aa34 = new javax.swing.JLabel();
        jPanel46 = new javax.swing.JPanel();
        Aa35 = new javax.swing.JLabel();
        jPanel47 = new javax.swing.JPanel();
        l4 = new javax.swing.JLabel();
        jPanel48 = new javax.swing.JPanel();
        Aa37 = new javax.swing.JLabel();
        jPanel49 = new javax.swing.JPanel();
        Aa38 = new javax.swing.JLabel();
        jPanel50 = new javax.swing.JPanel();
        Aa39 = new javax.swing.JLabel();
        jPanel51 = new javax.swing.JPanel();
        l8 = new javax.swing.JLabel();
        jPanel52 = new javax.swing.JPanel();
        Aa41 = new javax.swing.JLabel();
        jPanel53 = new javax.swing.JPanel();
        Aa42 = new javax.swing.JLabel();
        jPanel54 = new javax.swing.JPanel();
        Aa43 = new javax.swing.JLabel();
        jPanel55 = new javax.swing.JPanel();
        l12 = new javax.swing.JLabel();
        jPanel56 = new javax.swing.JPanel();
        Aa45 = new javax.swing.JLabel();
        jPanel57 = new javax.swing.JPanel();
        Aa46 = new javax.swing.JLabel();
        jPanel58 = new javax.swing.JPanel();
        Aa47 = new javax.swing.JLabel();
        b2 = new javax.swing.JTextField();
        c2 = new javax.swing.JTextField();
        B2 = new javax.swing.JTextField();
        C2 = new javax.swing.JTextField();
        l1 = new javax.swing.JTextField();
        l16 = new javax.swing.JTextField();
        l11 = new javax.swing.JTextField();
        l6 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        Limpiar = new java.awt.Button();
        fondo = new javax.swing.JLabel();

        jLabel5.setText("jLabel5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/cerrar (Copiar).png"))); // NOI18N
        btnCerrar.setContentAreaFilled(false);
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 0, 60, 50));

        btnMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/minimizar (Copiar) (Copiar) (Copiar).png"))); // NOI18N
        btnMinimizar.setContentAreaFilled(false);
        btnMinimizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinimizarActionPerformed(evt);
            }
        });
        getContentPane().add(btnMinimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 20, 30, 20));

        inicio.setBackground(new java.awt.Color(0, 0, 153));
        inicio.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dos.setBackground(new java.awt.Color(0, 0, 153));
        dos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(16, 153, 111));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(0, 102, 102));

        Bb.setForeground(new java.awt.Color(255, 255, 255));
        Bb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Bb, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Bb, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, 170, 130));

        jPanel8.setBackground(new java.awt.Color(0, 102, 102));

        Cc.setForeground(new java.awt.Color(255, 255, 255));
        Cc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Cc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Cc, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, 170, 130));

        B.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                BKeyTyped(evt);
            }
        });
        jPanel4.add(B, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, 140, 30));

        A.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                AKeyTyped(evt);
            }
        });
        jPanel4.add(A, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 140, 30));

        a.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                aKeyTyped(evt);
            }
        });
        jPanel4.add(a, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 50, 105));

        b.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                bKeyTyped(evt);
            }
        });
        jPanel4.add(b, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 50, 100));

        Aa.setEditable(false);
        Aa.setBackground(new java.awt.Color(204, 0, 0));
        Aa.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel4.add(Aa, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 170, 130));

        Dd.setEditable(false);
        Dd.setBackground(new java.awt.Color(204, 0, 0));
        Dd.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel4.add(Dd, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 210, 170, 130));

        jButton6.setText("F1");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 0, 50, -1));

        dos.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 480, 360));

        inicio.add(dos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 500));

        tres.setBackground(new java.awt.Color(0, 0, 153));
        tres.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel59.setBackground(new java.awt.Color(16, 153, 111));
        jPanel59.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel60.setBackground(new java.awt.Color(0, 102, 102));
        jPanel60.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Aa48.setForeground(new java.awt.Color(255, 255, 255));
        Aa48.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel60.add(Aa48, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 110));

        jPanel61.setBackground(new java.awt.Color(0, 102, 102));
        jPanel61.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Aa49.setForeground(new java.awt.Color(255, 255, 255));
        Aa49.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel61.add(Aa49, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 130, 80));

        jPanel60.add(jPanel61, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 120, 90));

        jPanel62.setBackground(new java.awt.Color(0, 102, 102));
        jPanel62.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Aa50.setForeground(new java.awt.Color(255, 255, 255));
        Aa50.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel62.add(Aa50, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 130, 80));

        jPanel63.setBackground(new java.awt.Color(0, 102, 102));
        jPanel63.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Aa51.setForeground(new java.awt.Color(255, 255, 255));
        Aa51.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel63.add(Aa51, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 130, 80));

        jPanel62.add(jPanel63, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 120, 90));

        jPanel60.add(jPanel62, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, 120, 90));

        jPanel59.add(jPanel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 190, 170, 110));

        jPanel64.setBackground(new java.awt.Color(0, 102, 102));

        Bb2.setForeground(new java.awt.Color(255, 255, 255));
        Bb2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel64Layout = new javax.swing.GroupLayout(jPanel64);
        jPanel64.setLayout(jPanel64Layout);
        jPanel64Layout.setHorizontalGroup(
            jPanel64Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel64Layout.createSequentialGroup()
                .addComponent(Bb2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel64Layout.setVerticalGroup(
            jPanel64Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel64Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Bb2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel59.add(jPanel64, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 70, 160, 110));

        jPanel66.setBackground(new java.awt.Color(0, 102, 102));

        Cc2.setForeground(new java.awt.Color(255, 255, 255));
        Cc2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel66Layout = new javax.swing.GroupLayout(jPanel66);
        jPanel66.setLayout(jPanel66Layout);
        jPanel66Layout.setHorizontalGroup(
            jPanel66Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Cc2, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
        );
        jPanel66Layout.setVerticalGroup(
            jPanel66Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Cc2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
        );

        jPanel59.add(jPanel66, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, 160, 110));

        A1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A1ActionPerformed(evt);
            }
        });
        A1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                A1KeyTyped(evt);
            }
        });
        jPanel59.add(A1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 120, 30));

        a1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                a1KeyTyped(evt);
            }
        });
        jPanel59.add(a1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 50, 90));

        jPanel68.setBackground(new java.awt.Color(0, 102, 102));
        jPanel68.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Aa53.setForeground(new java.awt.Color(255, 255, 255));
        Aa53.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel68.add(Aa53, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 110));

        jPanel69.setBackground(new java.awt.Color(0, 102, 102));
        jPanel69.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Aa54.setForeground(new java.awt.Color(255, 255, 255));
        Aa54.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel69.add(Aa54, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 130, 80));

        jPanel68.add(jPanel69, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 120, 90));

        jPanel59.add(jPanel68, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, 160, 110));

        jPanel70.setBackground(new java.awt.Color(0, 102, 102));
        jPanel70.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Aa55.setForeground(new java.awt.Color(255, 255, 255));
        Aa55.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel70.add(Aa55, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 110));

        jPanel71.setBackground(new java.awt.Color(0, 102, 102));
        jPanel71.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Aa56.setForeground(new java.awt.Color(255, 255, 255));
        Aa56.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel71.add(Aa56, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 130, 80));

        jPanel70.add(jPanel71, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 120, 90));

        jPanel72.setBackground(new java.awt.Color(0, 102, 102));
        jPanel72.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Aa57.setForeground(new java.awt.Color(255, 255, 255));
        Aa57.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel72.add(Aa57, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 130, 80));

        jPanel73.setBackground(new java.awt.Color(0, 102, 102));
        jPanel73.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Aa58.setForeground(new java.awt.Color(255, 255, 255));
        Aa58.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel73.add(Aa58, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 130, 80));

        jPanel72.add(jPanel73, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 120, 90));

        jPanel70.add(jPanel72, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, 120, 90));

        jPanel59.add(jPanel70, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 310, 160, 110));

        jPanel74.setBackground(new java.awt.Color(0, 102, 102));
        jPanel74.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Aa59.setForeground(new java.awt.Color(255, 255, 255));
        Aa59.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel74.add(Aa59, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 110));

        jPanel75.setBackground(new java.awt.Color(0, 102, 102));
        jPanel75.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Aa60.setForeground(new java.awt.Color(255, 255, 255));
        Aa60.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel75.add(Aa60, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 130, 80));

        jPanel74.add(jPanel75, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 120, 90));

        jPanel76.setBackground(new java.awt.Color(0, 102, 102));
        jPanel76.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Aa61.setForeground(new java.awt.Color(255, 255, 255));
        Aa61.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel76.add(Aa61, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 130, 80));

        jPanel77.setBackground(new java.awt.Color(0, 102, 102));
        jPanel77.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Aa62.setForeground(new java.awt.Color(255, 255, 255));
        Aa62.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel77.add(Aa62, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 130, 80));

        jPanel76.add(jPanel77, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 120, 90));

        jPanel74.add(jPanel76, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, 120, 90));

        jPanel59.add(jPanel74, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 70, 170, 110));

        b1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                b1KeyTyped(evt);
            }
        });
        jPanel59.add(b1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 50, 90));

        c1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                c1KeyTyped(evt);
            }
        });
        jPanel59.add(c1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 50, 90));

        B1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                B1KeyTyped(evt);
            }
        });
        jPanel59.add(B1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, 120, 30));

        C1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                C1KeyTyped(evt);
            }
        });
        jPanel59.add(C1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 20, 120, 30));

        Aa67.setEditable(false);
        Aa67.setBackground(new java.awt.Color(204, 0, 0));
        Aa67.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel59.add(Aa67, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 310, 170, 110));

        Aa63.setEditable(false);
        Aa63.setBackground(new java.awt.Color(204, 0, 0));
        Aa63.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel59.add(Aa63, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 160, 110));

        Dd3.setEditable(false);
        Dd3.setBackground(new java.awt.Color(204, 0, 0));
        Dd3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Dd3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Dd3ActionPerformed(evt);
            }
        });
        jPanel59.add(Dd3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 190, 160, 110));

        jButton5.setText("F1");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel59.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 0, 50, -1));

        tres.add(jPanel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 650, 450));

        inicio.add(tres, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 500));

        cuatro.setBackground(new java.awt.Color(0, 0, 153));
        cuatro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel9.setBackground(new java.awt.Color(16, 153, 111));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(0, 102, 102));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        l10.setForeground(new java.awt.Color(255, 255, 255));
        l10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel3.add(l10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 90));

        jPanel10.setBackground(new java.awt.Color(0, 102, 102));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Aa2.setForeground(new java.awt.Color(255, 255, 255));
        Aa2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel10.add(Aa2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 130, 80));

        jPanel3.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 120, 90));

        jPanel11.setBackground(new java.awt.Color(0, 102, 102));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Aa5.setForeground(new java.awt.Color(255, 255, 255));
        Aa5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel11.add(Aa5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 130, 80));

        jPanel12.setBackground(new java.awt.Color(0, 102, 102));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Aa6.setForeground(new java.awt.Color(255, 255, 255));
        Aa6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel12.add(Aa6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 130, 80));

        jPanel11.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 120, 90));

        jPanel3.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, 120, 90));

        jPanel9.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 140, 120, 90));

        jPanel13.setBackground(new java.awt.Color(0, 102, 102));

        l5.setForeground(new java.awt.Color(255, 255, 255));
        l5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(l5, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addComponent(l5, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel9.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, 120, 90));

        jPanel15.setBackground(new java.awt.Color(0, 102, 102));

        l2.setForeground(new java.awt.Color(255, 255, 255));
        l2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(l2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 91, Short.MAX_VALUE)
            .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel15Layout.createSequentialGroup()
                    .addComponent(l2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel9.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 120, 90));

        D2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D2ActionPerformed(evt);
            }
        });
        jPanel9.add(D2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 10, 120, 30));

        A2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A2ActionPerformed(evt);
            }
        });
        jPanel9.add(A2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 120, 30));

        a2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a2ActionPerformed(evt);
            }
        });
        jPanel9.add(a2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 50, 90));

        d2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                d2ActionPerformed(evt);
            }
        });
        jPanel9.add(d2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 50, 90));

        jPanel17.setBackground(new java.awt.Color(0, 102, 102));
        jPanel17.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        l3.setForeground(new java.awt.Color(255, 255, 255));
        l3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel17.add(l3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 90));

        jPanel18.setBackground(new java.awt.Color(0, 102, 102));
        jPanel18.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Aa7.setForeground(new java.awt.Color(255, 255, 255));
        Aa7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel18.add(Aa7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 130, 80));

        jPanel17.add(jPanel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 120, 90));

        jPanel9.add(jPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 120, 90));

        jPanel19.setBackground(new java.awt.Color(0, 102, 102));
        jPanel19.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        l7.setForeground(new java.awt.Color(255, 255, 255));
        l7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel19.add(l7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 90));

        jPanel20.setBackground(new java.awt.Color(0, 102, 102));
        jPanel20.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Aa9.setForeground(new java.awt.Color(255, 255, 255));
        Aa9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel20.add(Aa9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 130, 80));

        jPanel19.add(jPanel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 120, 90));

        jPanel21.setBackground(new java.awt.Color(0, 102, 102));
        jPanel21.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Aa10.setForeground(new java.awt.Color(255, 255, 255));
        Aa10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel21.add(Aa10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 130, 80));

        jPanel22.setBackground(new java.awt.Color(0, 102, 102));
        jPanel22.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Aa11.setForeground(new java.awt.Color(255, 255, 255));
        Aa11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel22.add(Aa11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 130, 80));

        jPanel21.add(jPanel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 120, 90));

        jPanel19.add(jPanel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, 120, 90));

        jPanel9.add(jPanel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, 120, 90));

        jPanel23.setBackground(new java.awt.Color(0, 102, 102));
        jPanel23.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        l9.setForeground(new java.awt.Color(255, 255, 255));
        l9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel23.add(l9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 90));

        jPanel24.setBackground(new java.awt.Color(0, 102, 102));
        jPanel24.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Aa13.setForeground(new java.awt.Color(255, 255, 255));
        Aa13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel24.add(Aa13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 130, 80));

        jPanel23.add(jPanel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 120, 90));

        jPanel25.setBackground(new java.awt.Color(0, 102, 102));
        jPanel25.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Aa14.setForeground(new java.awt.Color(255, 255, 255));
        Aa14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel25.add(Aa14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 130, 80));

        jPanel26.setBackground(new java.awt.Color(0, 102, 102));
        jPanel26.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Aa15.setForeground(new java.awt.Color(255, 255, 255));
        Aa15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel26.add(Aa15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 130, 80));

        jPanel25.add(jPanel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 120, 90));

        jPanel23.add(jPanel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, 120, 90));

        jPanel9.add(jPanel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 40, 120, 90));

        jPanel35.setBackground(new java.awt.Color(0, 102, 102));
        jPanel35.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        l13.setForeground(new java.awt.Color(255, 255, 255));
        l13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel35.add(l13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 120, 80));

        jPanel36.setBackground(new java.awt.Color(0, 102, 102));
        jPanel36.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Aa25.setForeground(new java.awt.Color(255, 255, 255));
        Aa25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel36.add(Aa25, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 130, 80));

        jPanel35.add(jPanel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 120, 90));

        jPanel37.setBackground(new java.awt.Color(0, 102, 102));
        jPanel37.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Aa26.setForeground(new java.awt.Color(255, 255, 255));
        Aa26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel37.add(Aa26, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 130, 80));

        jPanel38.setBackground(new java.awt.Color(0, 102, 102));
        jPanel38.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Aa27.setForeground(new java.awt.Color(255, 255, 255));
        Aa27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel38.add(Aa27, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 130, 80));

        jPanel37.add(jPanel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 120, 90));

        jPanel35.add(jPanel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, 120, 90));

        jPanel9.add(jPanel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 40, 120, 90));

        jPanel39.setBackground(new java.awt.Color(0, 102, 102));
        jPanel39.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        l14.setForeground(new java.awt.Color(255, 255, 255));
        l14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel39.add(l14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 90));

        jPanel40.setBackground(new java.awt.Color(0, 102, 102));
        jPanel40.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Aa29.setForeground(new java.awt.Color(255, 255, 255));
        Aa29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel40.add(Aa29, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 130, 80));

        jPanel39.add(jPanel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 120, 90));

        jPanel41.setBackground(new java.awt.Color(0, 102, 102));
        jPanel41.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Aa30.setForeground(new java.awt.Color(255, 255, 255));
        Aa30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel41.add(Aa30, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 130, 80));

        jPanel42.setBackground(new java.awt.Color(0, 102, 102));
        jPanel42.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Aa31.setForeground(new java.awt.Color(255, 255, 255));
        Aa31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel42.add(Aa31, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 130, 80));

        jPanel41.add(jPanel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 120, 90));

        jPanel39.add(jPanel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, 120, 90));

        jPanel9.add(jPanel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 140, 120, 90));

        jPanel43.setBackground(new java.awt.Color(0, 102, 102));
        jPanel43.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        l15.setForeground(new java.awt.Color(255, 255, 255));
        l15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel43.add(l15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 90));

        jPanel44.setBackground(new java.awt.Color(0, 102, 102));
        jPanel44.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Aa33.setForeground(new java.awt.Color(255, 255, 255));
        Aa33.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel44.add(Aa33, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 130, 80));

        jPanel43.add(jPanel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 120, 90));

        jPanel45.setBackground(new java.awt.Color(0, 102, 102));
        jPanel45.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Aa34.setForeground(new java.awt.Color(255, 255, 255));
        Aa34.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel45.add(Aa34, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 130, 80));

        jPanel46.setBackground(new java.awt.Color(0, 102, 102));
        jPanel46.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Aa35.setForeground(new java.awt.Color(255, 255, 255));
        Aa35.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel46.add(Aa35, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 130, 80));

        jPanel45.add(jPanel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 120, 90));

        jPanel43.add(jPanel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, 120, 90));

        jPanel9.add(jPanel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 240, 120, 90));

        jPanel47.setBackground(new java.awt.Color(0, 102, 102));
        jPanel47.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        l4.setForeground(new java.awt.Color(255, 255, 255));
        l4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel47.add(l4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 90));

        jPanel48.setBackground(new java.awt.Color(0, 102, 102));
        jPanel48.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Aa37.setForeground(new java.awt.Color(255, 255, 255));
        Aa37.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel48.add(Aa37, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 130, 80));

        jPanel47.add(jPanel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 120, 90));

        jPanel49.setBackground(new java.awt.Color(0, 102, 102));
        jPanel49.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Aa38.setForeground(new java.awt.Color(255, 255, 255));
        Aa38.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel49.add(Aa38, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 130, 80));

        jPanel50.setBackground(new java.awt.Color(0, 102, 102));
        jPanel50.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Aa39.setForeground(new java.awt.Color(255, 255, 255));
        Aa39.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel50.add(Aa39, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 130, 80));

        jPanel49.add(jPanel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 120, 90));

        jPanel47.add(jPanel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, 120, 90));

        jPanel9.add(jPanel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, 120, 90));

        jPanel51.setBackground(new java.awt.Color(0, 102, 102));
        jPanel51.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        l8.setForeground(new java.awt.Color(255, 255, 255));
        l8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel51.add(l8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 90));

        jPanel52.setBackground(new java.awt.Color(0, 102, 102));
        jPanel52.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Aa41.setForeground(new java.awt.Color(255, 255, 255));
        Aa41.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel52.add(Aa41, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 130, 80));

        jPanel51.add(jPanel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 120, 90));

        jPanel53.setBackground(new java.awt.Color(0, 102, 102));
        jPanel53.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Aa42.setForeground(new java.awt.Color(255, 255, 255));
        Aa42.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel53.add(Aa42, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 130, 80));

        jPanel54.setBackground(new java.awt.Color(0, 102, 102));
        jPanel54.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Aa43.setForeground(new java.awt.Color(255, 255, 255));
        Aa43.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel54.add(Aa43, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 130, 80));

        jPanel53.add(jPanel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 120, 90));

        jPanel51.add(jPanel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, 120, 90));

        jPanel9.add(jPanel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 340, 120, 90));

        jPanel55.setBackground(new java.awt.Color(0, 102, 102));
        jPanel55.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        l12.setForeground(new java.awt.Color(255, 255, 255));
        l12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel55.add(l12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 90));

        jPanel56.setBackground(new java.awt.Color(0, 102, 102));
        jPanel56.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Aa45.setForeground(new java.awt.Color(255, 255, 255));
        Aa45.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel56.add(Aa45, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 130, 80));

        jPanel55.add(jPanel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 120, 90));

        jPanel57.setBackground(new java.awt.Color(0, 102, 102));
        jPanel57.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Aa46.setForeground(new java.awt.Color(255, 255, 255));
        Aa46.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel57.add(Aa46, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 130, 80));

        jPanel58.setBackground(new java.awt.Color(0, 102, 102));
        jPanel58.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Aa47.setForeground(new java.awt.Color(255, 255, 255));
        Aa47.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel58.add(Aa47, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 130, 80));

        jPanel57.add(jPanel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 120, 90));

        jPanel55.add(jPanel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, 120, 90));

        jPanel9.add(jPanel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 340, 120, 90));

        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });
        jPanel9.add(b2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 50, 90));

        c2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c2ActionPerformed(evt);
            }
        });
        jPanel9.add(c2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 50, 90));

        B2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B2ActionPerformed(evt);
            }
        });
        jPanel9.add(B2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 120, 30));

        C2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C2ActionPerformed(evt);
            }
        });
        jPanel9.add(C2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, 120, 30));

        l1.setEditable(false);
        l1.setBackground(new java.awt.Color(204, 0, 0));
        l1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        l1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                l1ActionPerformed(evt);
            }
        });
        jPanel9.add(l1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 120, 90));

        l16.setEditable(false);
        l16.setBackground(new java.awt.Color(204, 0, 0));
        l16.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel9.add(l16, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 340, 120, 90));

        l11.setEditable(false);
        l11.setBackground(new java.awt.Color(204, 0, 0));
        l11.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel9.add(l11, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 240, 120, 90));

        l6.setEditable(false);
        l6.setBackground(new java.awt.Color(204, 0, 0));
        l6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        l6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                l6ActionPerformed(evt);
            }
        });
        jPanel9.add(l6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 120, 90));

        jButton4.setText("F1");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel9.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 10, -1, -1));

        cuatro.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 620, 450));

        inicio.add(cuatro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 500));

        getContentPane().add(inicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 740, 500));

        jButton1.setBackground(new java.awt.Color(0, 0, 153));
        jButton1.setFont(new java.awt.Font("Constantia", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(224, 224, 255));
        jButton1.setText("Dos");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, -1, -1));

        jButton2.setBackground(new java.awt.Color(0, 0, 153));
        jButton2.setFont(new java.awt.Font("Constantia", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(224, 224, 255));
        jButton2.setText("Tres");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, -1, -1));

        jButton3.setBackground(new java.awt.Color(0, 0, 153));
        jButton3.setFont(new java.awt.Font("Constantia", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(224, 224, 255));
        jButton3.setText("Cuatro");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 60, -1, -1));

        Limpiar.setLabel("Limpiar");
        Limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimpiarActionPerformed(evt);
            }
        });
        getContentPane().add(Limpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 70, 80, 40));
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnMinimizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinimizarActionPerformed
        this.setState(this.ICONIFIED);
    }//GEN-LAST:event_btnMinimizarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dos.setVisible(true);
        tres.setVisible(false);
        cuatro.setVisible(false);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dos.setVisible(false);
        tres.setVisible(true);
        cuatro.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
dos.setVisible(false);
        tres.setVisible(false);
        cuatro.setVisible(true);      
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void AKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AKeyTyped
    if(A.getText().length()>0){
            e();}
    }//GEN-LAST:event_AKeyTyped

    private void BKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BKeyTyped
     if(B.getText().length()>0){
            e();}
    }//GEN-LAST:event_BKeyTyped

    private void aKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_aKeyTyped
     if(a.getText().length()>0){
            e();}
    }//GEN-LAST:event_aKeyTyped

    private void bKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bKeyTyped
     if(b.getText().length()>0){
            e();}
    }//GEN-LAST:event_bKeyTyped

    private void A2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A2ActionPerformed
        if(A2.getText().length()>0){
            i();}
    }//GEN-LAST:event_A2ActionPerformed

    private void A1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_A1ActionPerformed

    private void A1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_A1KeyTyped
    if(A1.getText().length()>2){
            x();}
    }//GEN-LAST:event_A1KeyTyped

    private void B1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_B1KeyTyped
    if(B1.getText().length()>2){
            x();}
    }//GEN-LAST:event_B1KeyTyped

    private void C1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_C1KeyTyped
    if(C1.getText().length()>2){
            x();}
    }//GEN-LAST:event_C1KeyTyped

    private void a1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_a1KeyTyped
    if(a1.getText().length()>2){
            x();}
    }//GEN-LAST:event_a1KeyTyped

    private void b1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_b1KeyTyped
    if(b1.getText().length()>2){
            x();}
    }//GEN-LAST:event_b1KeyTyped

    private void c1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_c1KeyTyped
    if(c1.getText().length()>2){
            x();}
    }//GEN-LAST:event_c1KeyTyped

    private void B2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B2ActionPerformed
       if(B2.getText().length()>0){
            i();}
    }//GEN-LAST:event_B2ActionPerformed

    private void C2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C2ActionPerformed
       if(C2.getText().length()>0){
            i();}
    }//GEN-LAST:event_C2ActionPerformed

    private void D2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D2ActionPerformed
         if(D2.getText().length()>0){
            i();}
    }//GEN-LAST:event_D2ActionPerformed

    private void a2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a2ActionPerformed
         if(a2.getText().length()>0){
            i();}
    }//GEN-LAST:event_a2ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
         if(b2.getText().length()>0){
            i();}
    }//GEN-LAST:event_b2ActionPerformed

    private void c2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c2ActionPerformed
         if(c2.getText().length()>0){
            i();}
    }//GEN-LAST:event_c2ActionPerformed

    private void d2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_d2ActionPerformed
         if(d2.getText().length()>0){
            i();}
    }//GEN-LAST:event_d2ActionPerformed

    private void LimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimpiarActionPerformed
        l16.setText("");
        a.setText("");
        b.setText("");
        A.setText("");
        B.setText("");
        Aa.setText("");
        Bb.setText("");
        Cc.setText("");
        Dd.setText("");
        A2.setText("");
        a2.setText("");
        b2.setText("");
        c2.setText("");
        d2.setText("");
        B2.setText("");
        C2.setText("");
        D2.setText("");
        l1.setText("");
         l2.setText("");
          l3.setText("");
           l4.setText("");
            l5.setText("");
             l6.setText("");
              l7.setText("");
               l8.setText("");
                l9.setText("");
                 l10.setText("");
                  l11.setText("");
                   l12.setText("");
                    l13.setText("");
                     l14.setText("");
                      l15.setText("");
                      Aa.setText("");
         a1.setText("");
         b1.setText("");
         c1.setText("");
         A1.setText("");
         B1.setText("");
         C1.setText("");
         Aa67.setText("");
         Bb2.setText("");
         Aa59.setText("");
         Cc2.setText("");
         Aa67.setText("");
         Aa48.setText("");
         Aa53.setText("");
         Aa55.setText("");
         Aa67.setText("");
         Aa63.setText("");
         Dd3.setText("");
    }//GEN-LAST:event_LimpiarActionPerformed

    private void l1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_l1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_l1ActionPerformed

    private void l6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_l6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_l6ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       mensaje();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void Dd3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Dd3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Dd3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
      mensaje2();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        mensaje3();
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bioapp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bioapp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bioapp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bioapp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bioapp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField A;
    private javax.swing.JTextField A1;
    private javax.swing.JTextField A2;
    private javax.swing.JTextField Aa;
    private javax.swing.JLabel Aa10;
    private javax.swing.JLabel Aa11;
    private javax.swing.JLabel Aa13;
    private javax.swing.JLabel Aa14;
    private javax.swing.JLabel Aa15;
    private javax.swing.JLabel Aa2;
    private javax.swing.JLabel Aa25;
    private javax.swing.JLabel Aa26;
    private javax.swing.JLabel Aa27;
    private javax.swing.JLabel Aa29;
    private javax.swing.JLabel Aa30;
    private javax.swing.JLabel Aa31;
    private javax.swing.JLabel Aa33;
    private javax.swing.JLabel Aa34;
    private javax.swing.JLabel Aa35;
    private javax.swing.JLabel Aa37;
    private javax.swing.JLabel Aa38;
    private javax.swing.JLabel Aa39;
    private javax.swing.JLabel Aa41;
    private javax.swing.JLabel Aa42;
    private javax.swing.JLabel Aa43;
    private javax.swing.JLabel Aa45;
    private javax.swing.JLabel Aa46;
    private javax.swing.JLabel Aa47;
    private javax.swing.JLabel Aa48;
    private javax.swing.JLabel Aa49;
    private javax.swing.JLabel Aa5;
    private javax.swing.JLabel Aa50;
    private javax.swing.JLabel Aa51;
    private javax.swing.JLabel Aa53;
    private javax.swing.JLabel Aa54;
    private javax.swing.JLabel Aa55;
    private javax.swing.JLabel Aa56;
    private javax.swing.JLabel Aa57;
    private javax.swing.JLabel Aa58;
    private javax.swing.JLabel Aa59;
    private javax.swing.JLabel Aa6;
    private javax.swing.JLabel Aa60;
    private javax.swing.JLabel Aa61;
    private javax.swing.JLabel Aa62;
    private javax.swing.JTextField Aa63;
    private javax.swing.JTextField Aa67;
    private javax.swing.JLabel Aa7;
    private javax.swing.JLabel Aa9;
    private javax.swing.JTextField B;
    private javax.swing.JTextField B1;
    private javax.swing.JTextField B2;
    private javax.swing.JLabel Bb;
    private javax.swing.JLabel Bb2;
    private javax.swing.JTextField C1;
    private javax.swing.JTextField C2;
    private javax.swing.JLabel Cc;
    private javax.swing.JLabel Cc2;
    private javax.swing.JTextField D2;
    private javax.swing.JTextField Dd;
    private javax.swing.JTextField Dd3;
    private java.awt.Button Limpiar;
    private javax.swing.JTextField a;
    private javax.swing.JTextField a1;
    private javax.swing.JTextField a2;
    private javax.swing.JTextField b;
    private javax.swing.JTextField b1;
    private javax.swing.JTextField b2;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnMinimizar;
    private javax.swing.JTextField c1;
    private javax.swing.JTextField c2;
    private javax.swing.JPanel cuatro;
    private javax.swing.JTextField d2;
    private javax.swing.JPanel dos;
    private javax.swing.JLabel fondo;
    private javax.swing.JPanel inicio;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel35;
    private javax.swing.JPanel jPanel36;
    private javax.swing.JPanel jPanel37;
    private javax.swing.JPanel jPanel38;
    private javax.swing.JPanel jPanel39;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel40;
    private javax.swing.JPanel jPanel41;
    private javax.swing.JPanel jPanel42;
    private javax.swing.JPanel jPanel43;
    private javax.swing.JPanel jPanel44;
    private javax.swing.JPanel jPanel45;
    private javax.swing.JPanel jPanel46;
    private javax.swing.JPanel jPanel47;
    private javax.swing.JPanel jPanel48;
    private javax.swing.JPanel jPanel49;
    private javax.swing.JPanel jPanel50;
    private javax.swing.JPanel jPanel51;
    private javax.swing.JPanel jPanel52;
    private javax.swing.JPanel jPanel53;
    private javax.swing.JPanel jPanel54;
    private javax.swing.JPanel jPanel55;
    private javax.swing.JPanel jPanel56;
    private javax.swing.JPanel jPanel57;
    private javax.swing.JPanel jPanel58;
    private javax.swing.JPanel jPanel59;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel60;
    private javax.swing.JPanel jPanel61;
    private javax.swing.JPanel jPanel62;
    private javax.swing.JPanel jPanel63;
    private javax.swing.JPanel jPanel64;
    private javax.swing.JPanel jPanel66;
    private javax.swing.JPanel jPanel68;
    private javax.swing.JPanel jPanel69;
    private javax.swing.JPanel jPanel70;
    private javax.swing.JPanel jPanel71;
    private javax.swing.JPanel jPanel72;
    private javax.swing.JPanel jPanel73;
    private javax.swing.JPanel jPanel74;
    private javax.swing.JPanel jPanel75;
    private javax.swing.JPanel jPanel76;
    private javax.swing.JPanel jPanel77;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTextField l1;
    private javax.swing.JLabel l10;
    private javax.swing.JTextField l11;
    private javax.swing.JLabel l12;
    private javax.swing.JLabel l13;
    private javax.swing.JLabel l14;
    private javax.swing.JLabel l15;
    private javax.swing.JTextField l16;
    private javax.swing.JLabel l2;
    private javax.swing.JLabel l3;
    private javax.swing.JLabel l4;
    private javax.swing.JLabel l5;
    private javax.swing.JTextField l6;
    private javax.swing.JLabel l7;
    private javax.swing.JLabel l8;
    private javax.swing.JLabel l9;
    private javax.swing.JPanel tres;
    // End of variables declaration//GEN-END:variables
}
